### ISSUE TITLE
Nested accordions

### ISSUE THREAD

**Issue by intelligence** [nico3333fr/van11y-accessible-accordion-aria#4]
Hello, I'm back! :wink:

While using your great accordion I came across a use case where I want to have multiple accordions within another accordion. I set this up and ran into trouble, namely:
`Uncaught DOMException: Failed to execute 'insertBefore' on 'Node': The node before which the new node is to be inserted is not a child of this node.`

Is this something you'd able to look into?

Cheers, and thanks for this awesome accordion again!

**Comment by nico3333fr** [comment]
Hi!

A bit difficult to find, but I have good and bad news. ;)

In fact, the problem is coming from my selectors, which are rather cool. see https://github.com/nico3333fr/van11y-accessible-accordion-aria/blob/master/src/van11y-accessible-accordion-aria.es6.js#L164 
```
let $listAccordionsHeader = [].slice.call(accordion_node.querySelectorAll('' + ACCORDION_JS_HEADER));
```
for example gets all elements in accordion, without taking into account that some can be nested elements. And it is a global mess, everything goes wrong (as you reported). :-\

In fact, if I update the script to get only direct children like this (and everywhere this kind of selector is used):

```
let $listAccordionsHeader = [].slice.call(accordion_node.querySelectorAll(':scope > .' + ACCORDION_JS_HEADER));
```
It seems to solve the problem. So the problem is to select direct children. Good news!

Bad news: it seems this super cool feature `:scope` is not well supported https://developer.mozilla.org/en-US/docs/Web/CSS/%3ascope#Browser_compatibility 
I guess I will have to code a function to do it, and propose it in the script as an option (a kind of "stricter" mode to allow nested accordions).

Well :)

**Comment by nico3333fr** [comment]
Hi @intelligence !

Sorry for response time, I had to deal with several personal problems. 

Nested accordions are now working, as you will see in the demo: https://van11y.net/downloads/accordion/demo/index.html (second example)

The fixes have been published i last commit: https://github.com/nico3333fr/van11y-accessible-accordion-aria/commit/7e74707a396f08595630ce67f37d4e18aeee42a1

Cheers,
Nicolas

**Comment by iskrisis** [comment]
Hello, just noting that i don't think this still works fully. The nested accordions work but if you open them the parent accordion does not take into account their height. I think solutions i've seen others to use is to switch to height: auto after the transition but who knows.
